### ISSUE TITLE
Library Service Demo Flow

### ISSUE THREAD

**Issue by akhilojha** [requestly/content#18]
# Requestly : File Library Service
We have launched a new requestly service that manages your file. You can upload your files with the help of the service and get the url of uploaded file which you can use in requestly rules. To begin with this service supports only css and js files.

### Login
When you navigate to the library service it will ask you to login using your google account. This is required because we will internally be using your google drive to upload your files, we will create a folder in your google drive and then use it to manage all files that you upload.

![login](https://cloud.githubusercontent.com/assets/6073395/24347893/78948a34-12f7-11e7-9e64-e8b0eacc5e1d.PNG)

### Upload File
Once you login you will be shown file list page with a message "_You do not have any uploaded files_".
You need to click on the upload button on top right corner to upload any file. File explorer will open on clicking the button and you can select the file you want to upload.  _(Right now we support only js and css files, we will extend this to all files soon)_

![no_file](https://cloud.githubusercontent.com/assets/6073395/24348097/26ce054e-12f8-11e7-846b-b2e3c713a141.PNG)

### Edit Details
Once you have selected the file and its uploaded, we will show a dialog with file details. Here you have option to copy the url of uploaded file, adding description for uploaded file and editing file content.
Same file detail dialog can be opened by clicking on the file name of any uploaded file.

![upload_detail](https://cloud.githubusercontent.com/assets/6073395/24348327/ee119d64-12f8-11e7-9059-635399a0429a.PNG)

To add/update description just click on the edit icon and add description for the file that you want to upload. Once you are done, you can click the "green tick" button to add/update description.

![change_description](https://cloud.githubusercontent.com/assets/6073395/24348544/af2e5c4e-12f9-11e7-9d27-40416cbb4ba9.PNG)

### Edit File Content

Similarly you can click on "Edit File Content" button to edit the file that you just uploaded, we will open the file in our editor you that you can edit the file on fly. Once you save file after editing we will update the content of the file but the "URL" for file will remain unaffected.

![edit_file](https://cloud.githubusercontent.com/assets/6073395/24348621/f4ec0006-12f9-11e7-8e92-5eb7107cf968.PNG)

### File List

Once you have uploaded files, you can see them in the file list screen. Here you will have
* Name and description of all the files
* A button to copy url for the uploaded file.
* Edit icon button that will take you to editor and you can edit contents of that file.
* Delete icon button that you can use to delete the file.

![file_list](https://cloud.githubusercontent.com/assets/6073395/24348820/a6ca3e1e-12fa-11e7-943d-41f690909cf1.PNG)

**Comment by sachinjain024** [comment]
@akhilojha Looks nice..I will publish this article on this weekend.

**Comment by sachinjain024** [comment]
This article has been published. Closing this.
